class JsonStrings {
  static const listOfReports = '''
[
    {
      "id": 1,
      "report_no": "A01",
      "title": "test",
      "description": "test",
      "latitude": "2.274445",
      "longitude": "102.286357",
      "status": 3,
      "progress": "100",
      "remark_progress": "Barang dah sampai dengan selamat",
      "status_name": "proses",
      "created_at": "15/09/2023 03:53 PM",
      "updated_at": "20/09/2023 04:03 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Aiman"
    },
    {
      "id": 2,
      "report_no": "MLK20230915A0001",
      "title": "Kerosakan Jalan didepan Hospital Pantai, Melaka",
      "description": "-",
      "latitude": "2.2375582",
      "longitude": "102.2869622",
      "status": 2,
      "progress": "",
      "remark_progress": "selesai",
      "status_name": "ditugaskan",
      "created_at": "15/09/2023 03:53 PM",
      "updated_at": "20/09/2023 04:33 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "neo"
    },
    {
      "id": 3,
      "report_no": "A02",
      "title": "test",
      "description": "test",
      "latitude": "2.35",
      "longitude": "102.11667",
      "status": 2,
      "progress": "67",
      "remark_progress": "sedang dibaiki",
      "status_name": "ditugaskan",
      "created_at": "15/09/2023 03:53 PM",
      "updated_at": "20/09/2023 03:09 AM",
      "image": "detail image",
      "inspector": "neo",
      "reporter": "Aiman"
    },
    {
      "id": 4,
      "report_no": "MLK20230915A00002",
      "title": "kerosakan lampu jalan di depan amtis",
      "description": "mungkin rosak disebabkan vandalism oleh faiz akibat mimpi tol",
      "latitude": "2.317115",
      "longitude": "102.282371",
      "status": 5,
      "progress": "",
      "remark_progress": "tengah tunggu barang sampai",
      "status_name": "tolak",
      "created_at": "15/09/2023 04:32 AM",
      "updated_at": "18/09/2023 08:57 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Aiman"
    },
    {
      "id": 7,
      "report_no": "123",
      "title": "ayam",
      "description": "nasi ayam",
      "latitude": "2.274445",
      "longitude": "102.286357",
      "status": 2,
      "progress": "0",
      "remark_progress": "Sila buat",
      "status_name": "ditugaskan",
      "created_at": "18/09/2023 04:38 AM",
      "updated_at": "20/09/2023 04:39 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Daniel"
    },
    {
      "id": 8,
      "report_no": "456",
      "title": "itik",
      "description": "nasi itik",
      "latitude": "2.2375582",
      "longitude": "102.2869622",
      "status": 6,
      "progress": "",
      "remark_progress": "",
      "status_name": "tutup",
      "created_at": "18/09/2023 04:39 AM",
      "updated_at": "18/09/2023 07:28 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Daniel"
    },
    {
      "id": 9,
      "report_no": "789",
      "title": "lembu",
      "description": "nasi lembu",
      "latitude": "2.188431",
      "longitude": "102.249861",
      "status": null,
      "progress": "",
      "remark_progress": "",
      "status_name": "baru",
      "created_at": "18/09/2023 04:40 AM",
      "updated_at": "18/09/2023 07:08 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Daniel"
    },
    {
      "id": 10,
      "report_no": "KB20230918A00003",
      "title": "laporan jalan krubong",
      "description": "jalan banyak crack 1",
      "latitude": "2.1896",
      "longitude": "102.2501",
      "status": 2,
      "progress": "",
      "remark_progress": "",
      "status_name": "ditugaskan",
      "created_at": "18/09/2023 06:19 AM",
      "updated_at": "20/09/2023 05:06 AM",
      "image": "detail image",
      "inspector": "neo",
      "reporter": "Aiman"
    },
    {
      "id": 11,
      "report_no": "KB20230918A00004",
      "title": "laporan jalan krubong",
      "description": "jalan banyak crack 2",
      "latitude": "2.1882",
      "longitude": "102.2509",
      "status": 2,
      "progress": "100",
      "remark_progress": "sudah dibaiki",
      "status_name": "ditugaskan",
      "created_at": "18/09/2023 06:21 AM",
      "updated_at": "20/09/2023 01:23 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Aiman"
    },
    {
      "id": 12,
      "report_no": "KB20230919A00001",
      "title": "laporan jalan krubong 2",
      "description": "jalan banyak belubang",
      "latitude": "2.205685",
      "longitude": "102.256155",
      "status": 3,
      "progress": "",
      "remark_progress": "",
      "status_name": "proses",
      "created_at": "19/09/2023 08:14 AM",
      "updated_at": "19/09/2023 09:00 AM",
      "image": "detail image",
      "inspector": "",
      "reporter": "Aiman"
    }
  ]
  ''';

  static const listOfReportsFromApi = '''{
  "success": true,
  "data": [
    {
      "id": 1,
      "report_no": "A01",
      "title": "test",
      "description": "test",
      "latitude": "2.274445",
      "longitude": "102.286357",
      "status": 3,
      "progress": "100",
      "remark_progress": "Barang dah sampai dengan selamat",
      "status_name": "proses",
      "created_at": "15/09/2023 03:53 PM",
      "updated_at": "20/09/2023 04:03 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Aiman"
    },
    {
      "id": 2,
      "report_no": "MLK20230915A0001",
      "title": "Kerosakan Jalan didepan Hospital Pantai, Melaka",
      "description": "-",
      "latitude": "2.2375582",
      "longitude": "102.2869622",
      "status": 2,
      "progress": "",
      "remark_progress": "selesai",
      "status_name": "ditugaskan",
      "created_at": "15/09/2023 03:53 PM",
      "updated_at": "20/09/2023 04:33 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "neo"
    },
    {
      "id": 3,
      "report_no": "A02",
      "title": "test",
      "description": "test",
      "latitude": "2.35",
      "longitude": "102.11667",
      "status": 2,
      "progress": "67",
      "remark_progress": "sedang dibaiki",
      "status_name": "ditugaskan",
      "created_at": "15/09/2023 03:53 PM",
      "updated_at": "20/09/2023 03:09 AM",
      "image": "detail image",
      "inspector": "neo",
      "reporter": "Aiman"
    },
    {
      "id": 4,
      "report_no": "MLK20230915A00002",
      "title": "kerosakan lampu jalan di depan amtis",
      "description": "mungkin rosak disebabkan vandalism oleh faiz akibat mimpi tol",
      "latitude": "2.317115",
      "longitude": "102.282371",
      "status": 5,
      "progress": "",
      "remark_progress": "tengah tunggu barang sampai",
      "status_name": "tolak",
      "created_at": "15/09/2023 04:32 AM",
      "updated_at": "18/09/2023 08:57 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Aiman"
    },
    {
      "id": 7,
      "report_no": "123",
      "title": "ayam",
      "description": "nasi ayam",
      "latitude": "2.274445",
      "longitude": "102.286357",
      "status": 2,
      "progress": "0",
      "remark_progress": "Sila buat",
      "status_name": "ditugaskan",
      "created_at": "18/09/2023 04:38 AM",
      "updated_at": "20/09/2023 04:39 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Daniel"
    },
    {
      "id": 8,
      "report_no": "456",
      "title": "itik",
      "description": "nasi itik",
      "latitude": "2.2375582",
      "longitude": "102.2869622",
      "status": 6,
      "progress": "",
      "remark_progress": "",
      "status_name": "tutup",
      "created_at": "18/09/2023 04:39 AM",
      "updated_at": "18/09/2023 07:28 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Daniel"
    },
    {
      "id": 9,
      "report_no": "789",
      "title": "lembu",
      "description": "nasi lembu",
      "latitude": "2.188431",
      "longitude": "102.249861",
      "status": null,
      "progress": "",
      "remark_progress": "",
      "status_name": "baru",
      "created_at": "18/09/2023 04:40 AM",
      "updated_at": "18/09/2023 07:08 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Daniel"
    },
    {
      "id": 10,
      "report_no": "KB20230918A00003",
      "title": "laporan jalan krubong",
      "description": "jalan banyak crack 1",
      "latitude": "2.1896",
      "longitude": "102.2501",
      "status": 2,
      "progress": "",
      "remark_progress": "",
      "status_name": "ditugaskan",
      "created_at": "18/09/2023 06:19 AM",
      "updated_at": "20/09/2023 05:06 AM",
      "image": "detail image",
      "inspector": "neo",
      "reporter": "Aiman"
    },
    {
      "id": 11,
      "report_no": "KB20230918A00004",
      "title": "laporan jalan krubong",
      "description": "jalan banyak crack 2",
      "latitude": "2.1882",
      "longitude": "102.2509",
      "status": 2,
      "progress": "100",
      "remark_progress": "sudah dibaiki",
      "status_name": "ditugaskan",
      "created_at": "18/09/2023 06:21 AM",
      "updated_at": "20/09/2023 01:23 AM",
      "image": "detail image",
      "inspector": "Daniel",
      "reporter": "Aiman"
    },
    {
      "id": 12,
      "report_no": "KB20230919A00001",
      "title": "laporan jalan krubong 2",
      "description": "jalan banyak belubang",
      "latitude": "2.205685",
      "longitude": "102.256155",
      "status": 3,
      "progress": "",
      "remark_progress": "",
      "status_name": "proses",
      "created_at": "19/09/2023 08:14 AM",
      "updated_at": "19/09/2023 09:00 AM",
      "image": "detail image",
      "inspector": "",
      "reporter": "Aiman"
    }
  ],
  "message": "Papar semua aduan"
}''';
}
